### ISSUE TITLE
Agenda - DevOps Mutualization SIG Meeting - Thursday 20 May 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#24]
## Date
Thursday 20 May 2021 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-mutualization/issues/20)
- [x] DevOps approach at JPMC
- [x] Proposal for working group to document how banks are enabling automated change deployment (in partnership with [RegTech SIG](https://github.com/finos/open-regtech-sig))
- [x] Proposed topic for next few monthly meetings - [how are banks orchestrating self service DevOps workflows ](https://github.com/finos/devops-mutualization/issues/2)
- [x] Update on use of [Discussions](https://github.com/finos/devops-mutualization/blob/master/docs/Discussions.md)
- [x] AOB, Q&A & Adjourn (5mins)
  - DevOps World panel discussion update and call for panelists @mcleo-d - https://github.com/finos/devops-mutualization/issues/26#issuecomment-845044735 cc @tcraigjohnson

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-mutualization/

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by Arilova** [comment]
hi

**Comment by Ivan-Radovanovic** [comment]
Hello there 😊

**Comment by mcleo-d** [comment]
Thanks for saying hello @Arilova and @Ivan-Radovanovic - See you at the May meeting 😸

**Comment by ashukla13** [comment]
Hi everyone

**Comment by Ivan-Radovanovic** [comment]
hello friends

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by jbjonesjr** [comment]
👋  folks.  @pholleran is also here, but is not yet in the repo yet.

**Comment by jgavronsky** [comment]
Jane here, hello

**Comment by jpmsrh** [comment]
hi

**Comment by jpmsrh** [comment]
simon holt (JPMC)

**Comment by bhanafee** [comment]
Hello, this is Brian Hanafee

**Comment by pholleran** [comment]
👋

**Comment by tcraigjohnson** [comment]
@ashok how much effort did it take to build the evidence service and how much effort does it take to maintain it?

**Comment by tcraigjohnson** [comment]
Minutes/Notes of the meeting:

Agenda:
- Convene, roll call, welcome new people
- Tim Johnson, CloudBees
- James McLeod, FINOS
- Amol Shukla, Morgan Stanley
- Ashok Singh, JPMC
- Simon Holt, JPMC
- Brett Delle Grazie
- Ivan Radovinovic
- Arilova
- Jamie Jones, GitHub
- JGavronski
- Jpmrsh
- Brian Hanafee
- Edushak

-  Display FINOS Antitrust Policy summary slide

-  Approve previous meeting minutes
- Minutes approved

- James published the SIG meeting issues/discussion

- DevOps approach at JPMC
- Ashok Singh
- Overview of their approach to DevOps.  Security and compliance leads are embedded in the teams.  The amount of change determines the extent of testing - driven by policy.

- Focus on security, testing and compliance 
- Driven by developer community, not Security
- Each team has people identified that go through deep security and compliance training and then implement those efforts within the team
- 
- The Role of their end to end evidence service
- They’ve aggregated all the data from the SDLC pipeline and make it available real time to all stakeholders in a self-serve model
- 
- Single pane of glass to see the quality of the build, test coverage, etc.
- Now have better analytics and telemetry because of this evidence data.
- 
- Deployment authorization there is a human to review all the actions and evidence.  500+ applications using it  Now have Instant Change Authorization so long as you are using the evidence service.
- 
-  Proposal for working group to document how banks are enabling automated change deployment (in partnership with RegTech SIG)
- Amol asked the group if they are supportive, how to participate, start a discussion via pull request.
- James asked about expectations and encouraged people to step up, set expectations. James will help kick it off. Amol is interested. James committed to participating.

- Proposed topic for next few monthly meetings - how are banks orchestrating self service DevOps workflows

-  Update on use of Discussions

-  AOB, Q&A & Adjourn (5mins)
- DevOps World panel discussion update and call for panelists @mcleo-d - #26 (comment) cc @tcraigjohnson
- CFP closes 27-May - still time to get in a proposal

**Comment by mcleo-d** [comment]
>- Proposal for working group to document how banks are enabling automated change deployment (in partnership with RegTech SIG)
>- Amol asked the group if they are supportive, how to participate, start a discussion via pull request.
>- James asked about expectations and encouraged people to step up, set expectations. James will help kick it off. Amol is interested. James committed to participating.

The first **DevOps Mutualization : Automated Change Deployment Working Group** session has been proposed for Thursday 10th June 2021 - 10am EST / 3pm UK and the agenda can be found here ... #28 

Please add your thoughts to the comments of #28 as we confirm the date and time. I'll also let the [Regulation Innovation SIG](https://github.com/finos/open-regtech-sig/) know the working group is starting up. 

James 🚀
