### ISSUE TITLE
Open Source Security Panel at GDS Security Summit

### ISSUE THREAD

**Issue by mcleo-d** [finos/devops-mutualization#42]
# Open Source Security Panel at GDS Security Summit

FINOS is moderating an Open Source Security Panel at GDS Security Summit on **April 7th between 9:10am and 9:40am GMT** and has invited engineering and security leads from the FINOS Community to take part in the panel discussion and Q&A.

- **Moderator** - James McLeod, FINOS Director of Community.
- **Panellist 1** - FINOS member that is fully open source ready and collaborative.
- **Panellist 2** - FINOS member that is navigating their open source readiness, such as influencing stakeholders, teething pains etc
- **Panellist 3** - A Fintech that has a whole new approach to harnessing open source or maybe has a conflicting point of view.

## FINOS Community Invitation for Questions

The Open Source Security Panel invites members of the FINOS Community to use this GitHub Issue to ask questions in advance of the panel discussion at GDS Security Summit. Please feel free to ask as many questions as relevant for prioritisation by the panel.

## GDS Group and Security Summit details

- Welcoming 15,000 senior executives through our virtual doors for 60 major summits and over a 1600 roundtables, we are one of the most well connected global executive learning communities
- In its 12th year the GDS Security Summit is a highly valued closed door event where 200 senior leaders tackle the professions biggest challenges.
- Our Award winning platform offers one of the most impressive virtual summit experiences on the market.

## Core Themes of Summit

- How to meet the future of cyber security head on as organisations seek to build a culture of trust, democratisation and customer centric responsiveness.
- Preparing for the Security Savvy Board - Preparing for cyber committees, board mandates around resilience and investor interest in security as a competitive advantage
- The Machines Are Here! From RPA, Zero Trust Access, to Devices and Apps - The Rise of Machine Identity Management
Other keynotes and panels being curated.

### Improving organisational learning after a cyber-Incident
- The current landscape of 3rd party risk
- Cyber Resilience - How do you operationalise it - a financial services case study

**Comment by mcleo-d** [comment]
@robbkeayes, @grovesy, @peter-thomas-db and @rhyddian,

Thank you for agreeing to take part / help organise participants for the **Open Source Security Panel at GDS Security Summit** on **April 7th between 9:10am and 9:40am GMT**.

I've raised this issue to collect, prioritise and agree the questions and discussion points in advance of the panel discussion. It would be awesome if you could share this issue with the representatives from your banks.

I am aware we need limit the amount of people on the panel, so it would be great to agree one participant from each of the banks represented in this issue. This currently stands at **3x banks from the FINOS Community**.

Let me know if you have further questions.

Speak soon,

James.

**Comment by robmoffat** [comment]
Building on what @peter-thomas-db says, I think this is exactly the sort of thing FINOS should be championing.  We need consumers of OpenSource to be funding and contributing to the software they use, and Log4J is an excellent example of why that needs to be the case.  Also, LeftPad.

I think there are more things like this along the way:  Chrome extensions are a security minefield at the moment, with popular extensions being purchased by hackers to inject exploits.  Bad actors also try to get commit-rights on popular OSS in order to inject code into projects.  It's only a matter of time before this causes a major security issue.

**Comment by dtrace4linux** [comment]
Supply chain - has been inevitable for many years. The rise of software (in general, not just OSS), gives rise to the question of "do I trust this" (consider iPhone/android and locked down app stores). Whilst the bad actors have spent years refining the trojan tools to attack at scale, this means we need a way to validate and trust what is running (often in closed box environments, such as unrooted mobiles). Solving the problem is not easy. If we fast forward 10-20 years, all software will generate standardised manifests, and be a "selling" attribute. (Today, no-one understands it - in the future, it will be a mark of quality or attestation). We have a long way to go, because deciding how to use this, in so many scenarios is tricky. (I see an overlap with blockchain audit trails - and eventually we could see a join of these technical ideas).

**Comment by dtrace4linux** [comment]
Apologies, as prior comments are more brain dump reaction to the original ideas list.

- How does log4j affect our collective thinking on OSS

Log4j is important, because it provides a common frame of reference - across technology, across the business (consuming organisations), and general public. So many eyes have pored over this issue in the many organisations across the world - few have bothered to look at the code or the commits - the underlying issue is mostly uninteresting; except, where it highlights the supply chain weakness, and ability to audit/detect and remediation applications.

Every cyber/software issue like this (including struts, openssl, heart bleed etc) highlights some deficiency in our ability to determine scope and risk. So, each incident teaches us something.

More holistically, we as individuals or organisations, are not taking this personally - we don't get to blame people for this scenario, we get to analyse pipelines, policies, tools, and ability for an organisation to fire on all cylinders, to fix the issue. 

Whilst log4j was damn awful, it was a fire drill for the $next one.

**Comment by dtrace4linux** [comment]
Since this is a 30m discussion panel, I assume no material/slides are needed. And, given the brief time slot, we will need to orchestrate questions/responses and time limits - maybe even a dress rehearsal?

**Comment by peter-thomas-db** [comment]
I think it would be good to produce a 'run of show' script which covers the questions and basic responses.  I think the things above are a good start into what the questions and answers could be.  If we can formulate this into something then it will make my life much easier to get comms approval as I can just show them this script.
